export enum SocketState {
  OPENING = 'OPENING',
  PAIRING = 'PAIRING',
  UNPAIRED = 'UNPAIRED',
  UNPAIRED_IDLE = 'UNPAIRED_IDLE',
  CONNECTED = 'CONNECTED',
  TIMEOUT = 'TIMEOUT',
  CONFLICT = 'CONFLICT',
  UNLAUNCHED = 'UNLAUNCHED',
  PROXYBLOCK = 'PROXYBLOCK',
  TOS_BLOCK = 'TOS_BLOCK',
  SMB_TOS_BLOCK = 'SMB_TOS_BLOCK',
  DEPRECATED_VERSION = 'DEPRECATED_VERSION',
}
